spring:
  application:
    name: Payment
  datasource:
    url: jdbc:h2:mem:paydb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  port: 8084
