spring:
  application:
    name: Product
    
#  cloud:
#   discovery:
#     enabled: true
   
server:
  port: 8081



eureka:
  client:
#    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
